ARG MAVEN_VERSION
ARG GROUP_ID
ARG ARTIFACT_ID
ARG PROJECT_NAME
ARG MAIN_CLASS

FROM maven:${MAVEN_VERSION} AS builder
ARG GROUP_ID
ARG ARTIFACT_ID
ARG PROJECT_NAME
ARG MAIN_CLASS
WORKDIR /app
COPY ./code /app
RUN sed -i s/mycustomgroupid/${GROUP_ID}/g pom.xml
RUN sed -i s/mycustomartifactid/${ARTIFACT_ID}/g pom.xml
RUN sed -i s/mycustommainclass/${GROUP_ID}.${ARTIFACT_ID}.${MAIN_CLASS}/g pom.xml
RUN sed -i s/mycustomprojectname/${PROJECT_NAME}/g pom.xml